// Generated by gencpp from file emojime/ImageArray.msg
// DO NOT EDIT!


#ifndef EMOJIME_MESSAGE_IMAGEARRAY_H
#define EMOJIME_MESSAGE_IMAGEARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace emojime
{
template <class ContainerAllocator>
struct ImageArray_
{
  typedef ImageArray_<ContainerAllocator> Type;

  ImageArray_()
    : custom_msg()  {
    }
  ImageArray_(const ContainerAllocator& _alloc)
    : custom_msg(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _custom_msg_type;
  _custom_msg_type custom_msg;





  typedef boost::shared_ptr< ::emojime::ImageArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::emojime::ImageArray_<ContainerAllocator> const> ConstPtr;

}; // struct ImageArray_

typedef ::emojime::ImageArray_<std::allocator<void> > ImageArray;

typedef boost::shared_ptr< ::emojime::ImageArray > ImageArrayPtr;
typedef boost::shared_ptr< ::emojime::ImageArray const> ImageArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::emojime::ImageArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::emojime::ImageArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace emojime

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'emojime': ['/home/tepic/Documents/Cloud/NextCloud/_M21/Multimodal Interaction for Ubiquitous Computers/[06] Git-Codes/emojiMe/workspace/src/emojime/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::emojime::ImageArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::emojime::ImageArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::emojime::ImageArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::emojime::ImageArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::emojime::ImageArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::emojime::ImageArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::emojime::ImageArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34bc0b7b6938cfa2480828862cdaf1a1";
  }

  static const char* value(const ::emojime::ImageArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34bc0b7b6938cfa2ULL;
  static const uint64_t static_value2 = 0x480828862cdaf1a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::emojime::ImageArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "emojime/ImageArray";
  }

  static const char* value(const ::emojime::ImageArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::emojime::ImageArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string custom_msg\n\
";
  }

  static const char* value(const ::emojime::ImageArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::emojime::ImageArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.custom_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::emojime::ImageArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::emojime::ImageArray_<ContainerAllocator>& v)
  {
    s << indent << "custom_msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.custom_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EMOJIME_MESSAGE_IMAGEARRAY_H
