// Generated by gencpp from file messages/ImageArray.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_IMAGEARRAY_H
#define MESSAGES_MESSAGE_IMAGEARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace messages
{
template <class ContainerAllocator>
struct ImageArray_
{
  typedef ImageArray_<ContainerAllocator> Type;

  ImageArray_()
    : ImageArray()  {
    }
  ImageArray_(const ContainerAllocator& _alloc)
    : ImageArray(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::sensor_msgs::Image_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::Image_<ContainerAllocator> >::other >  _ImageArray_type;
  _ImageArray_type ImageArray;





  typedef boost::shared_ptr< ::messages::ImageArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages::ImageArray_<ContainerAllocator> const> ConstPtr;

}; // struct ImageArray_

typedef ::messages::ImageArray_<std::allocator<void> > ImageArray;

typedef boost::shared_ptr< ::messages::ImageArray > ImageArrayPtr;
typedef boost::shared_ptr< ::messages::ImageArray const> ImageArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages::ImageArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages::ImageArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'messages': ['/home/tepic/Documents/tepic/Git/emojiMe/workspace/src/messages/msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::messages::ImageArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::ImageArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::ImageArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::ImageArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::ImageArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::ImageArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages::ImageArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dad93653879502e47043038885f31507";
  }

  static const char* value(const ::messages::ImageArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdad93653879502e4ULL;
  static const uint64_t static_value2 = 0x7043038885f31507ULL;
};

template<class ContainerAllocator>
struct DataType< ::messages::ImageArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages/ImageArray";
  }

  static const char* value(const ::messages::ImageArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages::ImageArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image[] ImageArray\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of camera\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::messages::ImageArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages::ImageArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ImageArray);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages::ImageArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages::ImageArray_<ContainerAllocator>& v)
  {
    s << indent << "ImageArray[]" << std::endl;
    for (size_t i = 0; i < v.ImageArray.size(); ++i)
    {
      s << indent << "  ImageArray[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "    ", v.ImageArray[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_IMAGEARRAY_H
